export default  {
    ADD_CONTACT: 'ADD_CONTACT',
    DELETE_CONTACT: 'DELETE_CONTACT',
    UPDATE_CONTACT: 'UPDATE_CONTACT',
  
    SET_INPUT_TITLE: 'SET_INPUT_TITLE',
    SET_INPUT_CONTENT: 'SET_INPUT_CONTENT',
    SET_INPUT_ID: 'SET_INPUT_ID',
    RESET_INPUT: 'RESET_INPUT',
  }